### ISSUE TITLE
Linea del tiempo. Cuevas Hernández Erik Israel 

### ISSUE THREAD

**Issue by ErikCuevas03** [SistemasTecTlaxiaco/actividad-7-ErikCuevas03#1]
[linea del tiempo.pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-ErikCuevas03/files/9824470/linea.del.tiempo.pdf)

**Comment by Daisy-GonzalezLita12** [comment]
Muy bien hecho compañero 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
